###

# Obtener roles de pago
GET http://localhost:4000/api/rol/2?anio=2024&mes=Enero

###

#Crear roles
POST http://localhost:4000/api/rol

{
  "anio": 2024,
  "mes": "Enero"
}
###

#Obtener consolidado de vacaciones
GET http://localhost:4000/api/cons/vac?fechaDesde=undefined&fechaHasta=2024-09-12

###
