export { FondoLogo } from './FondoLogo/FondoLogo'
export { SideBar } from './SideBar/SideBar'
export { default as UpBar } from './UpBar/UpBar'
export { ButtonIcon } from './ButtonIcon/ButtonIcon'
export { Tabla } from './Tabla/Tabla'
export { FormModul } from './FormModul/FormModul'
export { CabReport } from './Cabecera/CabReport'
export { BotonFooter } from './BotonGuardar/BotonGuardar'
export { SelectBox } from './Select/SelectBox'
export { Modal } from './Modal/Modal'
export { DragAndDrop } from './DragAndDrop/DragAndDrop'
